[default]
TITLE = ""
SECRET_KEY = "dee86f03-af0f-4989-aa0b-443167e98efb"
ALGORITHM = 'HS512'
CACHE_TYPE = 'redis'
CACHE_REDIS_HOST = 'localhost'
CACHE_REDIS_PORT = 6379
CACHE_REDIS_DB = 0
CACHE_REDIS_URL = 'redis://localhost:6379/0'
CACHE_DEFAULT_TIMEOUT = 500
BUNDLE_ERRORS = true
SQLALCHEMY_DATABASE_URI = 'postgresql://admin:admin@db-serasa:5432/imobabranco'
EXTENSIONS = [
    #'src.extensions.database:init_app',
    'src.extensions.cache:init_app',
    'src.routes.blueprint:init_app',
]

[production]
