"""empty message

Revision ID: 33980ba7f81c
Revises: c7d218cb53f5
Create Date: 2023-05-25 11:50:11.133516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33980ba7f81c'
down_revision = 'c7d218cb53f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('cpf')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
